// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CalcPorcentagemTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void calcPorcentagem() {
    driver.get("https://www.mercadolivre.com.br//");
    driver.manage().window().setSize(new Dimension(945, 1012));
    js.executeScript("window.scrollTo(0,1418)");
    driver.findElement(By.linkText("Porcentagem")).click();
    js.executeScript("window.scrollTo(0,200)");
    driver.findElement(By.id("l11")).click();
    driver.findElement(By.id("l11")).sendKeys("20");
    driver.findElement(By.id("l12")).click();
    driver.findElement(By.id("l12")).sendKeys("50");
    driver.findElement(By.id("l21")).click();
    driver.findElement(By.id("l21")).sendKeys("10");
    driver.findElement(By.id("l22")).click();
    driver.findElement(By.id("l22")).click();
    driver.findElement(By.id("l22")).click();
    {
      WebElement element = driver.findElement(By.id("l22"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".tm-content")).click();
    driver.findElement(By.id("l23")).click();
    driver.findElement(By.id("l23")).sendKeys("9");
    driver.findElement(By.id("l32")).click();
    driver.findElement(By.id("l32")).sendKeys("50");
    driver.findElement(By.id("l33")).click();
    driver.findElement(By.id("l33")).sendKeys("85");
  }
}
