// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MercadoLivreBuscaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void mercadoLivreBusca() {
    driver.get("https://www.mercadolivre.com.br/");
    driver.manage().window().setSize(new Dimension(945, 1012));
    driver.findElement(By.id("cb1-edit")).click();
    driver.findElement(By.id("cb1-edit")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("cb1-edit")).sendKeys("luva de boxe");
    driver.findElement(By.id("cb1-edit")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("cb1-edit")).sendKeys("nissan kicks");
    {
      WebElement element = driver.findElement(By.id("cb1-opt1-3"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ui-search-top-keywords"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".nav-search")).click();
    driver.findElement(By.id("cb1-edit")).sendKeys("calculadora científica");
    {
      WebElement element = driver.findElement(By.id("cb1-opt1-1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".andes-tooltip__text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
  }
}
