// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MercadoLivreCategoriaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void mercadoLivreCategoria() {
    driver.get("https://www.mercadolivre.com.br/");
    driver.manage().window().setSize(new Dimension(945, 1012));
    js.executeScript("window.scrollTo(0,1800)");
    driver.findElement(By.cssSelector(".slick-slide:nth-child(1) .category:nth-child(1) > p")).click();
    driver.findElement(By.cssSelector(".slick-slide:nth-child(8) .carousel__item__1 img")).click();
    driver.findElement(By.cssSelector(".ui-search-filter-dl:nth-child(4) .ui-search-filter-container:nth-child(2) .ui-search-filter-results-qty")).click();
  }
}
